#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
 
npm run lint:staged 
 
 
 
. "$(dirname -- "$0")/_/husky.sh"
 
npm run lint:staged 
 
 
 
. "$(dirname -- "$0")/_/husky.sh"
 
npm run lint:staged 
 
 
 
. "$(dirname -- "$0")/_/husky.sh"
 
npm run lint:staged 
 
 
 
. "$(dirname -- "$0")/_/husky.sh"
 
npm run lint:staged 
 
 
 