"""Initial migration with cascade delete

Revision ID: 9d111e2bd46c
Revises: 
Create Date: 2025-05-04 22:04:08.660789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d111e2bd46c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint('actual_values_metric_id_fkey', 'actual_values', type_='foreignkey')
    op.drop_constraint('actual_values_shop_id_fkey', 'actual_values', type_='foreignkey')
    op.create_foreign_key(None, 'actual_values', 'metrics', ['metric_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actual_values', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_categories_status', table_name='categories')
    op.alter_column('metrics', 'unit',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('periods_year_quarter_month_key', 'periods', type_='unique')
    op.create_unique_constraint('unique_period', 'periods', ['year', 'quarter', 'month'])
    op.drop_constraint('plan_values_metric_id_fkey', 'plan_values', type_='foreignkey')
    op.drop_constraint('plan_values_shop_id_fkey', 'plan_values', type_='foreignkey')
    op.create_foreign_key(None, 'plan_values', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'plan_values', 'metrics', ['metric_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shops', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_shops_status', table_name='shops')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shops_status', 'shops', ['status'], unique=False)
    op.alter_column('shops', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'plan_values', type_='foreignkey')
    op.drop_constraint(None, 'plan_values', type_='foreignkey')
    op.create_foreign_key('plan_values_shop_id_fkey', 'plan_values', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key('plan_values_metric_id_fkey', 'plan_values', 'metrics', ['metric_id'], ['id'])
    op.drop_constraint('unique_period', 'periods', type_='unique')
    op.create_unique_constraint('periods_year_quarter_month_key', 'periods', ['year', 'quarter', 'month'])
    op.alter_column('metrics', 'unit',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Руб.'::character varying"),
               existing_nullable=False)
    op.create_index('idx_categories_status', 'categories', ['status'], unique=False)
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'actual_values', type_='foreignkey')
    op.drop_constraint(None, 'actual_values', type_='foreignkey')
    op.create_foreign_key('actual_values_shop_id_fkey', 'actual_values', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key('actual_values_metric_id_fkey', 'actual_values', 'metrics', ['metric_id'], ['id'])
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
